name: gazzer
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 0.0.1+5

environment:
  sdk: ^3.8.0

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

  fluttertoast: ^8.2.12
  flutter_localizations:
    sdk: flutter


  # core
  firebase_core: ^4.0.0
  firebase_messaging: ^16.0.0
  firebase_crashlytics: ^5.0.0
  firebase_analytics: ^12.0.0
  go_router: ^16.0.0

  flutter_local_notifications: ^19.3.0
  # internet_connection_checker_plus: ^2.7.2
  # upgrader: ^11.4.0
  # url_launcher: ^6.3.1
  package_info_plus: ^8.3.0
  shorebird_code_push: ^2.0.3


  #API
  dio: ^5.8.0+1
  pretty_dio_logger: ^1.4.0
  # freezed: ^2.4.8

  #UI
  flutter_svg: ^2.1.0
  animations: ^2.0.11
  smooth_page_indicator: ^1.2.1
  skeletonizer: ^2.0.1
  intl_phone_number_field: ^0.2.1
  confetti: ^0.8.0
  lottie: ^3.3.1
  flutter_rating_bar: ^4.0.1
  dotted_border: ^3.0.1
  circular_motion: ^0.0.6
  # 
  scrollable_list_tab_scroller: ^3.1.1
  # anchor_scroll_controller: ^0.4.4
  # flutter_sticky_header: ^0.8.0
  scrollable_positioned_list: ^0.3.8
  scrolls_to_top: ^2.1.1
  easy_sticky_header: ^1.1.1
  nested_scroll_view_plus: ^3.0.0
  ribbon_widget: ^1.0.5

  curve_slider: ^0.0.4
  timer_count_down: ^2.2.2
  odometer: ^3.0.0
  pinput: ^5.0.1
  hotspot: ^0.1.3
  carousel_slider: ^5.1.1
  # webview_flutter: ^4.12.0
  # tab_container: ^3.5.3
  # photo_view: ^0.15.0
  # video_player: ^2.9.2


  #others
  flutter_bloc: ^9.1.1 #state management
  get_it: ^8.0.3 #dependency injection 
  intl: ^0.20.2 #Format date
  equatable: ^2.0.7

  #Storage
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.2.4
  # isar: ^3.1.0+1

  # pickers
  # image_picker: ^1.1.2
  # file_picker: ^10.1.9
  # path_provider: ^2.1.5
  # open_filex: ^4.7.0
  # syncfusion_flutter_pdfviewer: ^29.2.5
  # table_calendar: ^3.2.0

  #handle image
  # http_parser: ^4.1.2
  cached_network_image: ^3.4.1

  #Location
  google_maps_flutter: ^2.12.2
  geolocator: ^14.0.1
  # intl_phone_number_field: ^0.2.1
  # location: ^5.0.0
  # app_settings: ^5.1.1
  # go_router: ^15.1.2
  event_bus: ^2.0.1
  flutter_multi_formatter: ^2.13.7
  # flutter_multi_formatter: ^2.13.7
  # share_plus: ^11.0.0
  # social
  google_sign_in: ^7.0.0
  sign_in_with_apple: ^7.0.1
  flutter_facebook_auth: ^7.1.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.5
  mockito: ^5.4.5
  bloc_test: ^10.0.0
  go_router_builder: 3.0.1
  build_runner: any
  build_verify: 3.1.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/png/
    - assets/fonts/
    - assets/svg/
    - assets/gif/
    - assets/lottie/
    - shorebird.yaml

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/poppins/Poppins-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/poppins/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/poppins/Poppins-BlackItalic.ttf
          weight: 900
          style: italic
    - family: inter
      fonts:
        - asset: assets/fonts/Inter.ttf
    - family: playfair
      fonts:
        - asset: assets/fonts/Playfair.ttf
flutter_assets:
  assets_path:
    - assets/
  output_path: lib/core/presentation/resources/
  filename: assets.dart
  ignore_comments: true
