name: Build test apk

on:
  push:
    branches:
      - dev_push
  pull_request:
    branches:
      - dev_push

jobs:
  build_test_apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # create key store files from secrets
      - name: Retrieve the secret key store and decode it to a file
        env:
          BASE_64_SIGNING_KEY: ${{ secrets.BASE_64_SIGNING_KEY }}
        run: |
          cd ./android/app
          ls -l 
          echo $BASE_64_SIGNING_KEY | base64 --decode > ./upload-keystore.jks
          echo "key store file created"
          ls -l

      # create key properties files from secrets
      - name: Retrieve key properties and decode it to a file
        env:
          BASE_64_KEY_PROPERTIES: ${{ secrets.BASE_64_KEY_PROPERTIES }}
        run: |
          cd ./android/
          ls -l
          echo $BASE_64_KEY_PROPERTIES | base64 --decode > key.properties
          echo "key properties file created"
          ls -l

      - name: Set up JDK 23.0.1+11
        uses: actions/setup-java@v2
        with:
          java-version: "23.0.1+11"
          distribution: "temurin"

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install Dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk

      - run: ls build/app/outputs/flutter-apk

      ############### Upload / Distribute apk ################
      #upload builded apk to an artifact in github
      # - name: Upload APK to Gihub artifacts
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: release-apk
      #     path: build/app/outputs/flutter-apk/app-release.apk

      # use this github actions to upload to firebase
      - name: upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.CI_FIREBASE_APP_ID }}
          token: ${{ secrets.CI_FIREBASE_TOKEN }}
          # serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: testers
          file: build/app/outputs/flutter-apk/app-release.apk
